apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sudosos
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/GEWIS/abc-deployments.git
  ref:
    branch: main
