---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bac-htpasswd
  namespace: webhost-prod
spec:
  encryptedData:
    htpasswd: AgCDMOqlp5KmvQAyz8EzawP/NmaYVyCu00oy5JGWR5FBa80iXS11jHn6jxmHq/L/IBl4ZziFpsp524DCYvSm4sEUGy5MeeLDlzPTYRlKsle6SEwxe7OSDOWrmnxVN7MF0tVLEKeou/2Rs9cCNp2k1Hkk9nOhmtqLuY53fCpF2etEPFke8a4+W1GwxqRlmpGr1TOy4gnIr68fUB3eeGIJAdwY3MFvZPAL42iaQU2JpWu9Umgt7alzVNioqp2eDSWCWwXcuPxS0bYcpKEvGwByOAMy6mu3+ryo9q8Qmv+UTxEgQWNpjlAXspjSPpX76Nhy0co5k0Fd0KxqP9r0SbgXCBZ5y3C69MajWAofYJLGuOXOd/55IDZjtosby0ksbAgeHfdayGYIRkK/ikCX6MXdqcWxYQitBsN7NuTTdU74C3o7YGpX03weIdZ/kQosOW9RsWuuxUcnZbqwvwAoTjUXdTqhmSSX/OcEq4oV6plI9eAZYfqkCFidnaplr95u7QjpeWB35sAk8HU6R3I1f4iuCyCtSjZ4yVsS8mgIJTESbrRJ7SGgQ2Gv5SN6S9lWO/m/UsMmiB5F2U4/U5WeoQHq+SvVrmwpq7rkv5TRmOD+0cGu7yDof6+OMKLEMSAjSAV1WVg0myYoobJLvHSODrfAD/+EUP3W4X+4m0xP9txbpUANsPB9vQ4PBk7/CGQGYyYHWKDF1W3JA/Pbq7JKJpeBO9V/HrIxSosNkckJFt9kdYcUz2euHX7B4FiG/g==
  template:
    metadata:
      name: bac-htpasswd
      namespace: webhost-prod
