apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: parelpracht
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/GEWIS/parelpracht.git
  ref:
    branch: gitops
