apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: webhost-prod
  namespace: flux-system
spec:
  interval: 10m
  releaseName: prod
  targetNamespace: webhost-prod
  storageNamespace: webhost-prod
  serviceAccountName: app-deployer
  chart:
    spec:
      chart: static-webhost
      version: 0.7.2
      sourceRef:
        kind: HelmRepository
        name: gewis-webhost
        namespace: flux-system
  values:
    domainGroups:
      - name: abc
        domains:
          - name: abc.gewis.nl
            writablePaths:
              - aoc_poster/cache
              - pr_poster/cache
        adminDomain: abc-admin.gewis.nl
        oidc:
          groups:
            - "Organ - ABC"
      - name: campus
        domains:
          - name: board.gewis.nl
          - name: fse.gewis.nl
          - name: fyc22-2.gewis.nl
          - name: fyc5050.gewis.nl
          - name: geduld.gewis.nl
          - name: gewiski.gewis.nl
          - name: intro22.gewis.nl
          - name: kleding.gewis.nl
          - name: mta-sts.gewis.nl
          - name: personal.gewis.nl
          - name: signature.gewis.nl
          - name: studytrip2025.gewis.nl
        oidc:
          groups: []
    storage:
      size: 10Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: webhost-prod
