apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: webhost-prod
  namespace: flux-system
spec:
  interval: 10m
  releaseName: prod
  targetNamespace: webhost-prod
  storageNamespace: webhost-prod
  serviceAccountName: app-deployer
  chart:
    spec:
      chart: static-webhost
      version: 0.7.2
      sourceRef:
        kind: HelmRepository
        name: gewis-webhost
        namespace: flux-system
  values:
    domainGroups:
      - name: abc
        domains:
          - name: abc.gewis.nl
            writablePaths:
              - aoc_poster/cache
              - pr_poster/cache
        adminDomain: abc-admin.gewis.nl
        oidc:
          groups:
            - "Organ - ABC"
      - name: gehack
        domains:
          - name: gehack.gewis.nl
        oidc:
          groups:
            - "Organ - GEHACK"
      - name: cbc-bbq
        domains:
          - name: cbc-bbq.gewis.nl
        oidc:
          groups: []
      - name: static
        domains:
          - name: static.gewis.nl
        oidc:
          groups:
            - "Organ - CBC"
      - name: stijl
        domains:
          - name: stijl.gewis.nl
        oidc:
          groups:
            - "Organ - CBC"
      - name: board
        domains:
          - name: vz.personal.gewis.nl
          - name: secr.personal.gewis.nl
          - name: pm.personal.gewis.nl
          - name: cib.personal.gewis.nl
          - name: co.personal.gewis.nl
          - name: ceb.personal.gewis.nl
        oidc:
          groups:
            - "Board - Current board"
      - name: mta-sts
        domains:
          - name: mta-sts.gewis.nl
        oidc:
          groups:
            - "Organ - CBC"
      - name: 9eglinster
        domains:
          - name: 9eglinster.gewis.nl
        oidc:
          groups:
            - "Organ - 9eglinster"
      - name: athena
        domains:
          - name: athena.gewis.nl
        oidc:
          groups:
            - "Organ - ATHENA"
      - name: defi
        domains:
          - name: defi.gewis.nl
        oidc:
          groups:
            - "Organ - Defi"
      - name: avico
        domains:
          - name: avico.gewis.nl
        oidc:
          groups:
            - "Organ - AViCo"
      - name: boom
        domains:
          - name: boom.gewis.nl
        oidc:
          groups:
            - "Organ - B.O.O.M."
      - name: gezwem
        domains:
          - name: gezwem.gewis.nl
        oidc:
          groups:
            - "Organ - GEZWEM"
      - name: intro
        domains:
          - name: intro.gewis.nl
        oidc:
          groups:
            - "Organ - Intro27"
      - name: linkinbio
        domains:
          - name: linkinbio.gewis.nl
        oidc:
          groups:
            - "Organ - GSM"
      - name: odc
        domains:
          - name: odc.gewis.nl
        oidc:
          groups:
            - "Organ - ODC"
      - name: ssg
        domains:
          - name: ssg.gewis.nl
        oidc:
          groups:
            - "Organ - SSG"
      
    storage:
      size: 20Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: webhost-prod
