apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: osticket-prod
  namespace: flux-system
spec:
  interval: 1m
  path: "./osticket"
  prune: true
  sourceRef:
    kind: GitRepository
    name: osticket
  serviceAccountName: app-deployer
  targetNamespace: osticket-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: osticket-prod
