apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: osticket
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/GEWIS/internal-systems.git
  ref:
    branch: main
